## Numpy

### 1. Numpy Array and Operation

- numpy의 기본적인 사용법에 대해서 배워봅니다.


- numpy에서 numpy.array를 만드는 여러가지 방법과 지원하는 연산자에 대해서 공부합니다.

<numpy array의 특징>
1. 모든 원소의 dtype이 같다. 전부 다 int거나 float다.

2. 연산의 의미가 조금 다르다. (broadcasting)

3. 대용량 array인 경우에 for 문을 직접 사용하는 것보다 
내부적으로 정의된 연산을 사용하는 것이 더 빠르다.

4. 생성 후에 크기 변경이 불가능하다. (원소 업데이트는 가능)
mutable object임. (tuple처럼 크기 번경, 원소 변경까지 안 되는 건 아님. 크기 변경은 됨.)

### 1.1. Numpy Array creation

In [1]:
# numpy 라이브러리를 불러옵니다.
import numpy as np

In [2]:
# 파이썬 리스트 선언
data = [1, 2, 3, 4]

In [3]:
# 파이썬 2차원 리스트(행렬) 선언
data2 = [[1, 2], 
         [3, 4]]

In [4]:
# 파이썬 list를 numpy array로 변환합니다.

# numpy array를 만드는 방식의 대부분은 파이썬 리스트를 np.array로 변환하는 방식입니다.
np.array(data)

array([1, 2, 3, 4])

In [10]:
# 2차원 리스트를 np.array로 만듭니다.
arr2 = np.array(data2) # data2라는 리스트를 numpy array로 만들어라.
arr2.shape
# 크기가 2짜리인 2차원 shape이다.

(2, 2)

In [3]:
# 0부터 9까지 숫자를 자동으로 생성한 array
np.arange(0, 10)
# 크기가 10짜리인 1차원 shape이다.
np.zeros(shape=(5,3))
# 주어진 shape의 크기에 맞게 0을 원소로 생성.
np.linspace(0, 1, 100) 
# [start, stop]에서 num개의 number를 균등한 구간으로 잘라서 원소를 생성.
# 0부터 1 사이의 숫자를 100개의 조각으로 쪼개서 array로 만들어 줌.
np.random.randn(5, 3)
# 주어진 shape을 가지는 sampling 표준정규분포에 따라 만들어 줌. 그래서 대부분 -1에서 1 사이의 숫자가 생성되게 됨.

array([[ 0.09097121,  2.50173591,  1.00204755],
       [-0.59603683,  0.91585876,  1.46266168],
       [-0.08963404,  1.25801616,  1.22460003],
       [ 1.7041107 ,  0.61183251, -3.0653303 ],
       [-0.18940486,  1.23466291,  0.13856907]])

In [14]:
# 10부터 99까지 숫자를 자동으로 생성한 array
np.arange(10, 100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

### 1.2. Reshaping array

In [19]:
# 3 x 3 행렬을 만들어봅시다.
# 1차원: vector
# 2차원: matrix(행렬)
# 3차원 이상: tensor
x = np.zeros(shape=(5, 3, 4, 5))
# shape을 이해해 보자. 가장 바깥 괄호부터 원소의 개수를 순차적으로 기록한 것.
# 가장 처음 숫자는 가장 바깥 괄호 안의 원소 개수다. 
# 두 번째 숫자는 두 번째 괄호 안의 원소 개수다. 
# 세 번째 숫자는 세 번째 괄호 안의 원소 개수다.
## 거꾸로 분석하고 싶을 때는 안 쪽 숫자부터 분석하는 것이 편하다.

x = np.zeros(shape=(32, 3, 224, 224))
### 이 코드는 대략 이런 식으로 분석할 수 있다.
### 224 X 224 크기의 3개(rgb) channel을 가지고 있는 이미지가 32개가 있다는 뜻.
x

array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]],


       [[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0.

In [7]:
# reshape을 이용하여 만들어봅시다.
x = np.arange(1, 10).reshape(9, 1)

## reshpae(9, 1)은 reshpae(9,)와 다르다.

y = np.arange(1, 10).reshape(9,)

## reshape(9)는 vector다. vector는 1차원 배열. 즉 row만 있는 거라고 생각하면 편함.

z = np.arange(1, 121).reshape(24, -1)

## -1을 써 주면, 원소 개수에 따라서 필요한 수치를 컴퓨터가 계산해 준다.

print(y)

[1 2 3 4 5 6 7 8 9]


In [ ]:
# row vector를 column vector로


In [ ]:
# 펼치기


### 1.3. Concatenation(합치기) of arrays

In [31]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# arr1 + arr2 = 원소들끼리 더한 값을 생성함.
arr1 + arr2
# arr1와 arr2를 합칩니다

array([5, 7, 9])

In [35]:
# stacking vertically
np.vstack([arr1, arr2])

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
# stacking horizontally
np.hstack([arr1, arr2])

array([1, 2, 3, 4, 5, 6])

## 1.4. Array Arithmetic (like vector) --> Universal Function

In [36]:
# v1 = (1, 2, 3), v2 = (4, 5, 6) 벡터 2개 생성하기.
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [37]:
# 리스트로 더하기 연산해보기
v1 + v2

array([5, 7, 9])

In [38]:
#  vector subtraction
v1 - v2

array([-3, -3, -3])

In [39]:
# (not vector operation) elementwise(원소끼리) multiplication
v1 * v2

array([ 4, 10, 18])

In [40]:
# (not vector operation) elementwise(원소끼리) division
v1 / v2

array([0.25, 0.4 , 0.5 ])

In [41]:
# dot product (같은 위치의 원소를 다 곱한 뒤 더해주는 연산 vector 개념인 듯.)
v1 @ v2

32

### 1.5. Broadcast and Universal Function

- 서로 크기가 다른 numpy array를 연산할 때, 자동으로 연산을 전파(broadcast)해주는 기능. 행렬곱 연산을 할 때 편리하다.

In [43]:
arr1 = np.array([1, 2, 3])

In [47]:
arr2 = np.array([[-1, -1, -1],
                [1, 1, 1]])

In [48]:
# 2개의 array를 더해보면?
arr1 + arr2 
# 연산이 작동함. 왜인 것일까? 셰잎 (3,) + 셰잎 (2, 3)을 더할 때
# 셰잎이 다르면, 낮은 차원의 셰잎이 같은지 살펴보고 같을 때 더해 줌.

array([[0, 1, 2],
       [2, 3, 4]])

In [49]:
# 2개의 array를 곱해보면? (**)
arr1 * arr2

array([[-1, -2, -3],
       [ 1,  2,  3]])

- Universal Function(일종의 트릭임) : broadcast 기능을 확장해서, numpy array의 모든 원소에 동일한 함수를 반복문으로 적용한 것과 같은 효과를 내는 기능.

In [51]:
# f = lambda x : 1/x
arr1 / 1  ## int -> float로 바꾸는 트릭.
1 / arr1  ## 각 원소를 reverse(역수로 바꿈) 연산.

def reverse_num(x):
    return 1/x
for i in range(len(arr1)):
    arr1[i] = reverse_num(arr1(i))
# 이 함수를 만들어서 원소에 적용한 것과 같이, numpy에서의 reverse연산은 간단하게 할 수 있음.

array([1., 2., 3.])

numpy, pandas, scipy 등은 cpu를 사용하는 라이브러리다.
gpu를 사용하는 라이브러리는 cduf(h20.ai), cuml(h20.ai), RAPIDS(Nvidia)등을 사용해야 한다.

In [ ]:
# f = lambda x : x + 2


### 1.6. Indexing


In [ ]:
arr1 = np.arange(10)

In [ ]:
# 첫번째 원소


In [ ]:
# 마지막 원소


In [ ]:
# 앞에서부터 원소 3개 slicing


In [ ]:
arr2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
arr2

In [ ]:
# arr2의 2row, 3column 원소 = 7


In [ ]:
# arr2의 세번째 column [3, 7, 11]


In [ ]:
# arr2의 두번째 row


## 2. Numpy Methods

- numpy에서 사용되는 여러가지 함수들을 사용해봅시다.

### 2.1. Math Functions 

In [10]:
# 표준정규분포에서 random sampling을 한 원소를 가지는 5x3 행렬을 만든다.
# pseudo-random: 현재 시각(ns(nano second)) 기준으로 생성

np.random.seed(42) # set seed number to 42
mat1 = np.random.randn(5, 3)
mat1

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439],
       [ 0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783]])

In [54]:
# mat1에 절대값 씌우기
np.abs(mat1)

array([[0.49671415, 0.1382643 , 0.64768854],
       [1.52302986, 0.23415337, 0.23413696],
       [1.57921282, 0.76743473, 0.46947439],
       [0.54256004, 0.46341769, 0.46572975],
       [0.24196227, 1.91328024, 1.72491783]])

In [55]:
# mat1 제곱하기
np.square(mat1)

array([[0.24672495, 0.01911702, 0.41950044],
       [2.31961994, 0.0548278 , 0.05482011],
       [2.49391312, 0.58895606, 0.2204062 ],
       [0.2943714 , 0.21475596, 0.2169042 ],
       [0.05854574, 3.66064129, 2.97534153]])

In [18]:
# mat1의 제곱근 구하기
# np.sqrt()가 제곱근 구하는 코드
# 만약 복소수(허수)까지 구하고 싶다면 astype('complex')까지 써주면 된다.
np.sqrt((mat1.astype('complex')))


array([[0.70477951+0.j        , 0.        +0.37183908j,
        0.80479099+0.j        ],
       [1.23411096+0.j        , 0.        +0.48389397j,
        0.        +0.48387701j],
       [1.25666734+0.j        , 0.87603352+0.j        ,
        0.        +0.68518201j],
       [0.73658675+0.j        , 0.        +0.68074789j,
        0.        +0.68244396j],
       [0.49189661+0.j        , 0.        +1.38321374j,
        0.        +1.31336127j]])

In [60]:
# linear algebra(선형대수학) functions
vec = np.array([1, 2, 3])

# 1. norm (행렬의 크기 계산. 즉 노름 계산)
np.linalg.norm(vec)

# 2. eigenvalue(선형대수학에 나오는 아이겐밸류)
mat = np.array([[1, 0],
               [0, 1]])
np.linalg.eig(mat)

EigResult(eigenvalues=array([1., 1.]), eigenvectors=array([[1., 0.],
       [0., 1.]]))

### 2.2. Aggregation(집계 라는 의미) functions 

In [21]:
np.random.seed(0xC0FFEE)
mat2 = np.random.rand(3, 2, 3) # randm은 표준정규분포에서 샘플링, rand는 연속균등분포에서 샘플링
mat2

array([[[0.57290783, 0.81519505, 0.92585076],
        [0.09358959, 0.26716135, 0.96059676]],

       [[0.34367795, 0.00781959, 0.86505672],
        [0.58423758, 0.57387893, 0.31362094]],

       [[0.47876059, 0.81577021, 0.82871562],
        [0.74794695, 0.9823008 , 0.22129689]]])

In [26]:
# Summation (axis = 0 이면 shape의 첫 번째 숫자(세로column 방향), 
# axis = 1은 shape의 두 번째 숫자(가로row 방향))
np.sum(mat2, axis=2)

array([[2.31395364, 1.32134771],
       [1.21655426, 1.47173745],
       [2.12324641, 1.95154464]])

In [ ]:
# mean
np.mean(mat2, axis=0)

In [ ]:
# std
np.std(mat2, axis=1)

In [27]:
# min, max ** axis 옵션을 쓸 수도 있음.
np.min(mat2)
np.max(mat2)

0.9823007965559496

In [ ]:
# 최소값 위치를 Index로 알려 줌.
np.argmin(mat2, axis=1)

In [9]:
# 최대값이 있는 Index
np.argmax(mat2, axis=0)

array([1, 2], dtype=int64)

In [13]:
# numpy dtype
# 데이터타입: int8(정수 하나 표현하는 데 8비트), int16, int32, int64
# 데이터타입: float32(실수 하나 표현하는 데 32비트), float64
# 데이터타입: uint8, uint16
print(f"int4 : -{2**3} ~ {2**3 - 1}")
print(f"int8 : -{2**7} ~ {2**7 - 1}")
print(f"int16 : -{2**15} ~ {2**15 - 1}")
print(f"int32 : -{2**31} ~ {2**31 - 1}")
print(f"int64 : -{2**63} ~ {2**63 - 1}")

# float16(half precision) vs float32(single precision) vs float64(double precision)

int4 : -8 ~ 7
int8 : -128 ~ 127
int16 : -32768 ~ 32767
int32 : -2147483648 ~ 2147483647
int64 : -9223372036854775808 ~ 9223372036854775807


In [11]:
# 그냥 정렬 (오름차순 정렬만 지원합니다)


In [ ]:
# index를 정렬


## 3. Performance Check

- Universal Function 기능을 통해 반복문을 사용한 것보다 훨씬 빠른 성능을 냅니다.


- 직접 실험을 통해 그 차이를 확인해보겠습니다.

In [14]:
np.random.seed(0)

def reverse_num(values):
    output = np.empty(len(values))
    
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    
    return output

In [15]:
# 1부터 100까지 범위에서 1000000개를 랜덤으로 뽑아서 array를 만듭니다.
big_array = np.random.randint(1, 100, 1000000)

In [16]:
%timeit reverse_num(big_array)

1.89 s ± 73.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [17]:
%timeit 1.0 / big_array

3.28 ms ± 47.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
## universal function을 쓰는 것이 훨씬 빠르다!